from flask import Flask, request, redirect, render_template, session, flash
from flask_sqlalchemy import SQLAlchemy
#importing correct modules for the databases; this imports the SQLAlchemy class form the sqlalchemy modules
app = Flask(__name__)
app.config['DEBUG'] = True
#make comment for equation for the below!
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://build-a-blog:Vagina1!@localhost:8889/build-a-blog'
#the connection string used to connect to our database
#create
app.config['SQLALCHEMY_ECHO'] = True
#object relationial mapping and debugging, this will provide or echo alot of the sql commands being generated by sql alchemy 
db = SQLAlchemy(app)
#create a database object via python code 
app.secret_key = 'y337kGcys&zP3B'

class Blog(db.Model): 

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    content= db.Column(db.Text())


    def __init__(self, title, content):
        self.title = title
        self.content = content
        
@app.route('/')
def index():
    title = "Build a Blog"
    blogs = Blog.query.order_by(Blog.id.desc()).all()
    return render_template('index.html', title=title, post=blogs)

@app.route('/blog')
def display_blog(): 
    post_id = request.args.get('id')
    mblog = Blog.query.get(post_id)
        #title = blog_title
    return render_template('details.html',blog=mblog)

@app.route('/newpost')
def create_new_post():
    blog_title = "" 
    blog_entry = ""
    title_error = ""
    content_error = "" 

    return render_template('newpost.html', title = "Add a new post", blog_title = blog_title, blog_entry= blog_entry, title_error = title_error, content_error = content_error)

 
@app.route('/newpost', methods=['POST'])
def do_new_post():
    new_blog_title = "" 
    new_blog_entry = ""
    title_error = ""
    content_error = "" 

    new_blog_title= request.form ['blog_title']
    new_blog_entry= request.form ['blog_entry']
    if len(new_blog_title)<1:
        title_error = "Please enter a title."

    if len(new_blog_entry)<1:
        content_error = "Please enter a post."
        
    if len(title_error)==0 and len(content_error)==0:
        new_post= Blog(new_blog_title, new_blog_entry)
        db.session.add(new_post) 
        db.session.commit()
        return redirect('/')
    else:
        return render_template('newpost.html', title = "Add a new post", blog_title = new_blog_title, blog_entry= new_blog_entry, title_error = title_error, content_error = content_error)

    

             
if __name__ == '__main__':
    app.run()